### ISSUE TITLE
add const in most places

### ISSUE THREAD

**Issue by KrisThielemans** [gschramm/parallelproj#1]
We need `forward_proj(const float image, float* sino, ...), i.e. declare objects pointed to as `const` as much as possible. Best practice, but will also prevent ugly copies and `const_cast` in STIR

**Comment by gschramm** [comment]
should be resolved now. all "read-only" arrays are now "const float *" / "const int *". Can you check if that works for STIR?

**Comment by KrisThielemans** [comment]
can't check it yet, as we don't use it yet! Should be fine though. I think you can close this.

**Comment by KrisThielemans** [comment]
seems all fine.
