### ISSUE TITLE
Torch example:  "requires_grad=True" and CUDA out of memory

### ISSUE THREAD

**Issue by lhellfh** [gschramm/parallelproj#67]
Hello!

In the current version of examples/07_torch/01_run_projection_layer.py the error 
_"ValueError: gradcheck expects at least one input tensor to require gradient, but none of the them have requires_grad=True."_ 
occurs when a ListModePETProjector is used instead of RegularPolygonPETProjector.

Is this behavior to be expected? 
Thank you in advance for your answer.

My environment (Anaconda):
Python 3.9
Pytorch 2.2.1
Pytorch CUDA 11.8
Installation of parallelproj via "conda install -c conda-forge parallelproj"

**Comment by gschramm** [comment]
Reducing the number of elements in:
- the image (input to the forward model)
- the "forward projection" of the image (output of the forward model)
will decrease the memory requirement. 

If you want to test whether your custom pytorch layers are implemented correctly, I recommend doing that
on a minimal image / sinogram. The implementation of these layers should be independent of the
actual input/output sizes of the used custom linear operator.

Note that available GPU-memory is always a concern when training recon-networks with realistic
3D PET data.

**Comment by lhellfh** [comment]
Thank you for the suggestion. I am now checking the gradients with very few LORs and it is working when I am adjusting the tolearnaces a bit. 
Best regards!
