### ISSUE TITLE
Issue regarding the list-mode negative Poisson log-likelihood function

### ISSUE THREAD

**Issue by zjutk** [gschramm/parallelproj#80]
Dear Professor Georg Schramm,

I recently reviewed the various algorithm examples in the Iterative Listmode Algorithm Examples and noticed your expression for the list-mode negative Poisson log-likelihood function: 

![image](https://github.com/user-attachments/assets/2df6adde-7e3c-42c4-bedc-bdfbca3f20ad)

I would like to confirm with you whether this expression aligns with the Listmode re-formulation of the sinogram-based minimization problem in your paper "Fast and memory-efficient reconstruction of sparse Poisson data in listmode with non-smooth priors with application to time-of-flight PET."

Additionally, I observed that your expression for the list-mode negative Poisson log-likelihood function appears to differ from those mentioned in other literature, such as:

>  ![1721359550424](https://github.com/user-attachments/assets/c29c1696-848c-44f4-aae1-898f70d22d0d)
#K. Ote, F. Hashimoto, Y. Onishi, T. Isobe and Y. Ouchi, "List-Mode PET Image Reconstruction Using Deep Image Prior," in IEEE Transactions on Medical Imaging, vol. 42, no. 6, pp. 1822-1834, June 2023, doi: 10.1109/TMI.2023.3239596.

Can these two expressions be considered fundamentally equivalent?

I look forward to your response. Thank you!

Sincerely,
Kun Tian

**Comment by gschramm** [comment]
Hi Kun,

1. The equation from our paper is the negative Poisson logL using sinogram data (y and \bar(y)) are sinograms and the sum runs over all sinogram bins "i".
2. The definition of Ote is equivalent except for:
- a global minus sign (they define the logL, we the negative logL)
- they ignore additive contaminations such as scatter and randoms

To see that they are equivalent, consider this:

$$logL = \sum_i y_i \log \bar{y_i} - \sum_i \bar{y_i} $$

now rewrite $y_i$ as 

$$y_i = \sum_1^{y_i} 1$$ 

(the counts in sinogram bin "i" are a sum of ones $y_i$ times)

$$logL = \sum_i \sum_1^{y_i} \log \bar{y_i} - \sum_i \bar{y_i} $$

the first two sums can be rewritten as the sum over all events (with event index $t$ and corresponding sinogram bin $i_t$)

$$logL = \sum_{events \ t} \log \bar{y}_{i(t)} - \sum_i \bar{y_i} $$

If we now insert the forward model (ignoring scatter and randoms)

$$\bar{y_i} = \sum_j a_{ij} x_j$$

we get the expression of Ote et al.
